# Question 4

In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [3]:
# read the csv
movies_awards = pd.read_csv('../Data/movies_awards.csv')
movies_awards.head(3)

totalSeasons Plot Rated Response Language  \
0         none  NaN   NaN     True  English   
1         none  NaN   NaN     True  Swedish   
2         none  NaN   NaN     True  English   

                                               Title Country  \
0  Book of Love: The Definitive Reason Why Men Ar...     USA   
1                              Anderssons älskarinna  Sweden   
2                                          Bad Blood      UK   

                         Writer  Metascore  imdbRating    ...      \
0  Jeffrey W. Byrd; Eric George        NaN         6.6    ...       
1                           NaN        NaN         7.4    ...       
2                 Tony Marchant        NaN         5.6    ...       

      Released                                             Actors  Year  \
0  14 Feb 2002  40 Glocc; Angelle Brooks; David Brown; Qadr Ca...  2002   
1  12 Feb 2001  Jakob Eklund; Ebba Forsberg; Örjan Landström; ...  2001   
2  11 Jan 2001  Emilia Fox; Serban Celea; Alex Jennings; Steve...  2001   

             Genre Awards  Runtime   Type Poster imdbVotes     imdbID  
0  Romance; Comedy    NaN   91 min  movie    NaN      79.0  tt0156376  
1            Drama    NaN  347 min  movie    NaN      34.0  tt0201374  
2              NaN    NaN      NaN  movie    NaN       8.0  tt0207989  

[3 rows x 21 columns]

In [185]:
# only keep selected columns
df = movies_awards.loc[:,['Title','Awards']]

In [186]:
# show
df.head(3)

Title Awards
0  Book of Love: The Definitive Reason Why Men Ar...    NaN
1                              Anderssons älskarinna    NaN
2                                          Bad Blood    NaN

In [187]:
# convert the type for further operatin
df['Awards'] = df['Awards'].astype('str') 
df

Title  \
0      Book of Love: The Definitive Reason Why Men Ar...   
1                                  Anderssons älskarinna   
2                                              Bad Blood   
3                                           Who Are You?   
4                                Skeletons in the Closet   
5                                     Cheerleader Ninjas   
6                                    The Girl from Paris   
7                                      The Final Curtain   
8                                                  Crush   
9                                         Happy Birthday   
10                                         Run Like Hell   
11                                       Crazy/Beautiful   
12                                 A Death in the Family   
13                                 The Anniversary Party   
14                                    Life as We Know It   
15                                    The Quiet American   
16                                     100 Centre Street   
17                                              90-60-90   
18                                    Like Cat and Mouse   
19                                    The Abduction Club   
20                                       In Love and War   
21                                      The Sign of Four   
22                     Adrian Mole: The Cappuccino Years   
23                            Amores querer con alevosía   
24                                      Punch-Drunk Love   
25                                                 Romeo   
26                                              The Kiss   
27                                           Avoir su...   
28                              Academia de baile Gloria   
29                                          Cet amour-là   
...                                                  ...   
15357                                            Beyhadh   
15358                                            BroShow   
15359        Lost Souls: On the Road with 'Blood Father'   
15360                             Hot Tub Party Massacre   
15361                                     All in Kitchen   
15362                                               Alex   
15363  All Access Nashville: Celebrating the CMA Awar...   
15364                         When a Snail Falls in Love   
15365                                       Celebs React   
15366                                     Catching Kelce   
15367                                            Armenia   
15368                                              Boss!   
15369                          Call of Duty: Revelations   
15370                   China: Between Clouds and Dreams   
15371                                Fresh Off the Porch   
15372                                       Thanksgiving   
15373                            Prison; My Parents & Me   
15374                                               Sara   
15375                                              Elegy   
15376                            Continent 7: Antarctica   
15377                                          Thank You   
15378                             Black Is the New Black   
15379                        Asian Entertainment Tonight   
15380                           Dragon Ball: Xenoverse 2   
15381                           Back in Time for Brixton   
15382  BET Presents Love & Happiness: An Obama Celebr...   
15383                                         The Plague   
15384          The Dark Knight Returns: An Epic Fan Film   
15385                                      Come Together   
15386                                              Binge   

                                                  Awards  
0                                                    nan  
1                                                    nan  
2                                                    nan  
3                                 1 win & 2 nominations.  
4                                  

In [188]:
# check the value form
df['Awards'][df.Title == 'Seabiscuit'].values[0]

'Nominated for 7 Oscars. Another 6 wins & 36 nominations.'

In [241]:
# a glance into the form of 'award' col
df['Awards'].unique()[0:50]

array(['nan', '1 win & 2 nominations.', '1 win.', '1 nomination.',
       '3 wins & 2 nominations.', '1 win & 1 nomination.',
       '5 nominations.', '2 wins & 5 nominations.',
       'Nominated for 1 Oscar. Another 13 wins & 13 nominations.',
       '5 wins & 4 nominations.',
       'Nominated for 1 Golden Globe. Another 14 wins & 34 nominations.',
       '22 wins & 44 nominations.', '1 win & 3 nominations.',
       '1 win & 8 nominations.', '2 nominations.',
       '6 wins & 1 nomination.',
       'Won 2 Golden Globes. Another 68 wins & 201 nominations.',
       'Won 1 Golden Globe. Another 31 wins & 143 nominations.',
       'Nominated for 4 Primetime Emmys. Another 16 nominations.',
       '3 wins & 6 nominations.', '2 wins.', '6 wins & 4 nominations.',
       '7 wins & 6 nominations.', '9 wins & 30 nominations.',
       'Won 1 Primetime Emmy. Another 1 win & 6 nominations.',
       'Nominated for 3 BAFTA Film Awards. Another 11 wins & 39 nominations.',
       '6 nominations.', '1

In [190]:
# use regex
import re

# wins & nominations

In [191]:
# sample test
g = '3 wins & 5 nominations'
# pattern
pattern_win = re.compile(r'(\d) win')
# check whether matches
match = pattern_win.match(g)
print(match)
if match:
    print("1111")
#check the value form

print(match.group().split(' ')[0])

<_sre.SRE_Match object; span=(0, 5), match='3 win'>
1111
3


In [192]:
# apply the regex and split a new col from the old
df['Award_wins'] = df['Awards'].apply(lambda x: pattern_win.match(x).group().split(' ')[0] if pattern_win.match(x) else 0)

In [193]:
#check
df.head(6)

Title                  Awards  \
0  Book of Love: The Definitive Reason Why Men Ar...                     nan   
1                              Anderssons älskarinna                     nan   
2                                          Bad Blood                     nan   
3                                       Who Are You?  1 win & 2 nominations.   
4                            Skeletons in the Closet                  1 win.   
5                                 Cheerleader Ninjas           1 nomination.   

  Award_wins  
0          0  
1          0  
2          0  
3          1  
4          1  
5          0

In [194]:
# check the data
df['Award_wins'].unique()

array([0, '1', '3', '2', '5', '6', '7', '9', '8', '4'], dtype=object)

In [195]:
g = '3 wins & 5 nominations'
pattern_nominations = re.compile(r'\b(\d)\b.*\bnominations\b')
match = pattern_nominations.match(g)
print(match)
if match:
    print("1111")
print(match.group().split(' ')[-2])

<_sre.SRE_Match object; span=(0, 22), match='3 wins & 5 nominations'>
1111
5


In [196]:
df['Award_nominated'] = df['Awards'].apply(lambda x: pattern_nominations.match(x).group().split(' ')[-2] if pattern_nominations.match(x) else 0)

In [197]:
df.head(7)

Title                   Awards  \
0  Book of Love: The Definitive Reason Why Men Ar...                      nan   
1                              Anderssons älskarinna                      nan   
2                                          Bad Blood                      nan   
3                                       Who Are You?   1 win & 2 nominations.   
4                            Skeletons in the Closet                   1 win.   
5                                 Cheerleader Ninjas            1 nomination.   
6                                The Girl from Paris  3 wins & 2 nominations.   

  Award_wins Award_nominated  
0          0               0  
1          0               0  
2          0               0  
3          1               2  
4          1               0  
5          0               0  
6          3               2

In [198]:
df['Award_nominated'].unique()

array([0, '2', '5', '4', '3', '8', '6', '30', '7', '9', '11', '34', '10',
       '15', '20', '12', '14', '17', '32', '25', '19', '13', '27', '16',
       '42', '23', '28', '21', '31', '29', '18', '53', '41', '33', '22',
       '26'], dtype=object)

# Oscar Nominated & Won

In [199]:
pattern_oscar_nominated = re.compile(r'Nominated for (\d) Oscars')

In [242]:
s = 'Nominated for 7 Oscars'
match = pattern_oscar_nominated .match(s)
print(match)
if match:
    print("1111")

<_sre.SRE_Match object; span=(0, 22), match='Nominated for 7 Oscars'>
1111


In [201]:
match.group().split(' ')[2]

'7'

In [202]:
df['oscar_nominated'] = df['Awards'].apply(lambda x: pattern_oscar_nominated .match(x).group().split(' ')[2] if pattern_oscar_nominated .match(x) else 0)

In [203]:
df.head()

Title                  Awards  \
0  Book of Love: The Definitive Reason Why Men Ar...                     nan   
1                              Anderssons älskarinna                     nan   
2                                          Bad Blood                     nan   
3                                       Who Are You?  1 win & 2 nominations.   
4                            Skeletons in the Closet                  1 win.   

  Award_wins Award_nominated oscar_nominated  
0          0               0               0  
1          0               0               0  
2          0               0               0  
3          1               2               0  
4          1               0               0

In [204]:
df['oscar_nominated'].unique()

array([0, '7', '3', '2', '5', '4'], dtype=object)

In [205]:
g = 'Won 3 Oscars'
pattern_oscar_won = re.compile(r'Won (\d) Oscars')
match = pattern_oscar_won.match(g)
print(match)
if match:
    print("1111")
print(match.group().split(' ')[1])

<_sre.SRE_Match object; span=(0, 12), match='Won 3 Oscars'>
1111
3


In [206]:
df['Oscar_Won'] = df['Awards'].apply(lambda x: pattern_oscar_won.match(x).group().split(' ')[1] if pattern_oscar_won.match(x) else 0)
df.head()

Title                  Awards  \
0  Book of Love: The Definitive Reason Why Men Ar...                     nan   
1                              Anderssons älskarinna                     nan   
2                                          Bad Blood                     nan   
3                                       Who Are You?  1 win & 2 nominations.   
4                            Skeletons in the Closet                  1 win.   

  Award_wins Award_nominated oscar_nominated Oscar_Won  
0          0               0               0         0  
1          0               0               0         0  
2          0               0               0         0  
3          1               2               0         0  
4          1               0               0         0

In [207]:
df['Oscar_Won'].unique()

array([0, '6', '3', '2', '7', '4'], dtype=object)

# Golden glob nominated & won

In [208]:
g = 'Nominated for 1 Golden Globe'

In [209]:
pattern_Golden_nominated = re.compile(r'Nominated for (\d) Golden Globe')

In [210]:
match = pattern_Golden_nominated.match(g)
print(match)
if match:
    print("1111")

<_sre.SRE_Match object; span=(0, 28), match='Nominated for 1 Golden Globe'>
1111


In [211]:
match.group().split(' ')[2]

'1'

In [212]:
df['Golden_Globe_nominated'] = df['Awards'].apply(lambda x: pattern_Golden_nominated .match(x).group().split(' ')[2] if pattern_Golden_nominated .match(x) else 0)

In [213]:
df.head()

Title                  Awards  \
0  Book of Love: The Definitive Reason Why Men Ar...                     nan   
1                              Anderssons älskarinna                     nan   
2                                          Bad Blood                     nan   
3                                       Who Are You?  1 win & 2 nominations.   
4                            Skeletons in the Closet                  1 win.   

  Award_wins Award_nominated oscar_nominated Oscar_Won Golden_Globe_nominated  
0          0               0               0         0                      0  
1          0               0               0         0                      0  
2          0               0               0         0                      0  
3          1               2               0         0                      0  
4          1               0               0         0                      0

In [214]:
df['Golden_Globe_nominated'].unique()

array([0, '1', '2', '3', '6'], dtype=object)

In [215]:
g = 'Won 1 Golden Globe'
pattern_golden_won = re.compile(r'Won (\d) Golden Globe')
match = pattern_golden_won.match(g)
print(match)
if match:
    print("1111")
print(match.group().split(' ')[1])

<_sre.SRE_Match object; span=(0, 18), match='Won 1 Golden Globe'>
1111
1


In [216]:
df['Golden_Globe_Won'] = df['Awards'].apply(lambda x: pattern_golden_won.match(x).group().split(' ')[1] if pattern_golden_won.match(x) else 0)
df.head()


Title                  Awards  \
0  Book of Love: The Definitive Reason Why Men Ar...                     nan   
1                              Anderssons älskarinna                     nan   
2                                          Bad Blood                     nan   
3                                       Who Are You?  1 win & 2 nominations.   
4                            Skeletons in the Closet                  1 win.   

  Award_wins Award_nominated oscar_nominated Oscar_Won Golden_Globe_nominated  \
0          0               0               0         0                      0   
1          0               0               0         0                      0   
2          0               0               0         0                      0   
3          1               2               0         0                      0   
4          1               0               0         0                      0   

  Golden_Globe_Won  
0                0  
1                0  
2                0  
3                0  
4                0

In [217]:
df['Golden_Globe_Won'].unique()

array([0, '2', '1', '6', '3'], dtype=object)

# Primetime Emmy nominated and won

In [218]:
g = 'Nominated for 1 Primetime Emmy'
pattern_Primetime_nominated = re.compile(r'Nominated for (\d) Primetime Emmy')
match = pattern_Primetime_nominated.match(g)
print(match)
if match:
    print("1111")

<_sre.SRE_Match object; span=(0, 30), match='Nominated for 1 Primetime Emmy'>
1111


In [219]:
match.group().split(' ')[2]

'1'

In [220]:
df['Primetime_Emmy_nominated'] = df['Awards'].apply(lambda x: pattern_Primetime_nominated .match(x).group().split(' ')[2] if pattern_Primetime_nominated .match(x) else 0)

In [221]:
df.head()

Title                  Awards  \
0  Book of Love: The Definitive Reason Why Men Ar...                     nan   
1                              Anderssons älskarinna                     nan   
2                                          Bad Blood                     nan   
3                                       Who Are You?  1 win & 2 nominations.   
4                            Skeletons in the Closet                  1 win.   

  Award_wins Award_nominated oscar_nominated Oscar_Won Golden_Globe_nominated  \
0          0               0               0         0                      0   
1          0               0               0         0                      0   
2          0               0               0         0                      0   
3          1               2               0         0                      0   
4          1               0               0         0                      0   

  Golden_Globe_Won Primetime_Emmy_nominated  
0                0                        0  
1                0                        0  
2                0                        0  
3                0                        0  
4                0                        0

In [222]:
df['Primetime_Emmy_nominated'].unique()

array([0, '4', '1', '2', '3', '5', '7'], dtype=object)

In [223]:
g = 'Won 3 Primetime Emmys'
pattern_Primetime_won = re.compile(r'Won (\d) Primetime Emmys')
match = pattern_Primetime_won.match(g)
print(match)
if match:
    print("1111")
print(match.group().split(' ')[1])

<_sre.SRE_Match object; span=(0, 21), match='Won 3 Primetime Emmys'>
1111
3


In [224]:
df['Primetime_Emmys_Won'] = df['Awards'].apply(lambda x: pattern_Primetime_won.match(x).group().split(' ')[1] if pattern_Primetime_won.match(x) else 0)
df.head()

Title                  Awards  \
0  Book of Love: The Definitive Reason Why Men Ar...                     nan   
1                              Anderssons älskarinna                     nan   
2                                          Bad Blood                     nan   
3                                       Who Are You?  1 win & 2 nominations.   
4                            Skeletons in the Closet                  1 win.   

  Award_wins Award_nominated oscar_nominated Oscar_Won Golden_Globe_nominated  \
0          0               0               0         0                      0   
1          0               0               0         0                      0   
2          0               0               0         0                      0   
3          1               2               0         0                      0   
4          1               0               0         0                      0   

  Golden_Globe_Won Primetime_Emmy_nominated Primetime_Emmys_Won  
0                0                        0                   0  
1                0                        0                   0  
2                0                        0                   0  
3                0                        0                   0  
4                0                        0                   0

In [225]:
df['Primetime_Emmys_Won'].unique()

array([0, '3', '2', '5', '7', '9', '4'], dtype=object)

# BAFTA nominated and won

In [226]:
g = 'Nominated for 1 BAFTA Film Award'
pattern_BAFTA_nominated = re.compile(r'Nominated for (\d) BAFTA Film Award')
match = pattern_BAFTA_nominated.match(g)
print(match)
if match:
    print("1111")
print(match.group().split(' ')[2])

<_sre.SRE_Match object; span=(0, 32), match='Nominated for 1 BAFTA Film Award'>
1111
1


In [227]:
df['BAFTA_Film_nominated'] = df['Awards'].apply(lambda x: pattern_BAFTA_nominated.match(x).group().split(' ')[2] if pattern_BAFTA_nominated.match(x) else 0)

In [228]:
df.head()

Title                  Awards  \
0  Book of Love: The Definitive Reason Why Men Ar...                     nan   
1                              Anderssons älskarinna                     nan   
2                                          Bad Blood                     nan   
3                                       Who Are You?  1 win & 2 nominations.   
4                            Skeletons in the Closet                  1 win.   

  Award_wins Award_nominated oscar_nominated Oscar_Won Golden_Globe_nominated  \
0          0               0               0         0                      0   
1          0               0               0         0                      0   
2          0               0               0         0                      0   
3          1               2               0         0                      0   
4          1               0               0         0                      0   

  Golden_Globe_Won Primetime_Emmy_nominated Primetime_Emmys_Won  \
0                0                        0                   0   
1                0                        0                   0   
2                0                        0                   0   
3                0                        0                   0   
4                0                        0                   0   

  BAFTA_Film_nominated  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0

In [229]:
df['BAFTA_Film_nominated'].unique()

array([0, '3', '1'], dtype=object)

In [230]:
g = 'Won 3 BAFTA Film Award'
pattern_BAFTA_won = re.compile(r'Won (\d) BAFTA Film Award')
match = pattern_BAFTA_won.match(g)
print(match)
if match:
    print("1111")
print(match.group().split(' ')[1])

<_sre.SRE_Match object; span=(0, 22), match='Won 3 BAFTA Film Award'>
1111
3


In [231]:
df['BAFTA_Film_won'] = df['Awards'].apply(lambda x: pattern_BAFTA_won.match(x).group().split(' ')[2] if pattern_BAFTA_won.match(x) else 0)

In [232]:
df.head()

Title                  Awards  \
0  Book of Love: The Definitive Reason Why Men Ar...                     nan   
1                              Anderssons älskarinna                     nan   
2                                          Bad Blood                     nan   
3                                       Who Are You?  1 win & 2 nominations.   
4                            Skeletons in the Closet                  1 win.   

  Award_wins Award_nominated oscar_nominated Oscar_Won Golden_Globe_nominated  \
0          0               0               0         0                      0   
1          0               0               0         0                      0   
2          0               0               0         0                      0   
3          1               2               0         0                      0   
4          1               0               0         0                      0   

  Golden_Globe_Won Primetime_Emmy_nominated Primetime_Emmys_Won  \
0                0                        0                   0   
1                0                        0                   0   
2                0                        0                   0   
3                0                        0                   0   
4                0                        0                   0   

  BAFTA_Film_nominated  BAFTA_Film_won  
0                    0               0  
1                    0               0  
2                    0               0  
3                    0               0  
4                    0               0

In [233]:
df['BAFTA_Film_won'].unique()

array([0])

# save to csv

In [237]:
df.to_csv('question4out.csv', encoding='utf-8')

In [239]:
www = pd.read_csv('question4out.csv')

In [240]:
www.head()

Unnamed: 0                                              Title  \
0           0  Book of Love: The Definitive Reason Why Men Ar...   
1           1                              Anderssons älskarinna   
2           2                                          Bad Blood   
3           3                                       Who Are You?   
4           4                            Skeletons in the Closet   

                   Awards  Award_wins  Award_nominated  oscar_nominated  \
0                     NaN           0                0                0   
1                     NaN           0                0                0   
2                     NaN           0                0                0   
3  1 win & 2 nominations.           1                2                0   
4                  1 win.           1                0                0   

   Oscar_Won  Golden_Globe_nominated  Golden_Globe_Won  \
0          0                       0                 0   
1          0                       0                 0   
2          0                       0                 0   
3          0                       0                 0   
4          0                       0                 0   

   Primetime_Emmy_nominated  Primetime_Emmys_Won  BAFTA_Film_nominated  \
0                         0                    0                     0   
1                         0                    0                     0   
2                         0                    0                     0   
3                         0                    0                     0   
4                         0                    0                     0   

   BAFTA_Film_won  
0               0  
1               0  
2               0  
3               0  
4               0